### PR TITLE
Added a little more introduction to before the 'Type Something' prompt

### PR DESCRIPTION
**Pull request by synthetixa**
I'm interested in your project. I'm a C and Java programmer for the most part. Recently, I've grown a fondness of operating systems. However, it's a much too daunting task to write on on my own; I know very little assembly. I was looking for recently updated OS projects on Github and I found this.

So, yeah. I'd love to help out. Have an explanatory message before 'Type Something'. I hope you like it!

### CODE REVIEW

**Comment by Whirligig231** [comment]
Hey synthetixa,

Thanks for your interest in the project! If you'd like to contribute more stuff than just a single printout, by all means feel free to do so. I'd appreciate it if you let me know in advance for any major changes just to make sure I don't accidentally code the same thing, but no worries. :)

**Comment by synthetixa** [comment]
Thanks for merging. This PR was kind of a test to see if you wanted help, but yes, thank you. I will contribute what I can and I'll make sure to notify you of big stuff. I'm happy to help and also to have something to do. Is the stuff in the Makefile okay?

**Comment by synthetixa** [comment]
Because if the files don't exist, I remember rm gives a warning. I guess it's not that important. I just don't like leaving stuff like that.

Don't know how much sense that makes. I can change it, if it matters.

**Comment by Whirligig231** [comment]
Yeah, the warning shouldn't matter. Plus, I only imagine it would give the warning if there are _no_ files to clean up, in which case the warning might actually be appropriate.

One slight question: how would you like to be credited in the code? Currently I'm the sole person listed in everything, including the MIT license.

**Comment by synthetixa** [comment]
I don't really know much about licensing. it depends on how large of a role I end up playing, I guess. It's named after you, so we most certainly should leave you as lead developer. I don't care about being put in the license all that much. It's your project. Just credit me in the readme as developer or co-developer or something, if that's okay. I'll fix the Makefile.

**Comment by synthetixa** [comment]
Also, might there be a better form of contact than this PR?

**Comment by Whirligig231** [comment]
Do you have Skype? I'm at whirligig231 on that.

**Comment by synthetixa** [comment]
Sure. Will add you now.

**Pull request merged**
